#!/bin/sh

echo "РАзработчик: Климанов Михаил"
echo "Название:  Информация пользователя"
echo "Запрашивает имя пользователя, если указанный пользователь зарегистрирован в системе, то выводит его уникальный идентификатор и имена групп в которые входит этот пользователь"

while true
do
read -p "Введите имя пользователя: " username
if id -u "$username" >/dev/null 2>&1; then
echo "UID: $(id -u "$username")"
echo "Группы: $(id -Gn "$username" | tr ' ' '\n')"
echo "Основная группа: $(id -gn "$username")"
else
echo "Пользователь не найден" >/dev/sdterr
fi
while true
do
echo "Хотете продолжить? (y\n)"
read cont
case "$cont" in
"y") echo ""; break;;
"n") echo ""; echo "Выход из программы"; exit $?;;
* ) echo "Ошибка, введите y,n" >/dev/stderr;;
esac
done
done
